### ISSUE TITLE
错别字

### ISSUE THREAD

**Issue by leenstx** [Re-Ch-Love/egui-doc-cn#2]
在 [README_zh-hans.md](https://github.com/Re-Ch-Love/egui-doc-cn/blob/main/README_zh-hans.md) 中第 172 行的 `喝` 应该是 `和`

**Comment by unclemate** [comment]
开个PR来修复吧

**Comment by Re-Ch-X** [comment]
抱歉，前段时间在忙别的事情没看github，已merge。感谢！
